title: tracy paige's digital journal
author: tracy paige
email: tracypaigewrites@gmail.com
description: my favorite reads
url: "https://tracypaigereads.github.io"
favicon: img/icon.jpg
show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
#theme: moving
remote_theme: huangyz0918/moving

moving:
  avatar_url: img/profile.jpg
  about_you: coder, reader, writer
  date_format: "%b %d" # date format of posts in home page
  back_to: "entries"

  # generate social links in about page.
  social_links:
    # twitter:
    # dribbble:
    # flickr:
    # instagram:
    # pinterest:
    # youtube:
    # youtube_channel:
    # youtube_channel_name:
    # telegram:
    # googleplus:
    # microdotblog:
    # reddit:

    # Mastodon instances
    # mastodon:
    # - username:
    #   instance:
    # - username:
    #   instance:

plugins:
  - jekyll-feed
  - jekyll-seo-tag
